/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Studente
 * Created: 7-mag-2018
 */

drop table utente;
create table utente (
    id integer primary key generated by default as identity,
    nome varchar(32),
    cognome varchar(32),
    email varchar(64) unique,
    urlImgProfile varchar(32),
    password varchar(32),
    isAutore integer
);

drop table notizia;
create table notizia (
    id integer primary key generated by default as identity,
    titolo varchar(32) unique,
    content varchar(1024),
    url varchar(64),
    categoria integer,
    autore integer references utente(id)
);
